@startuml

Entity usertype{
* PK usertypeid SERIAL
}

entity gymuser{
* PK userid INT
--
* FK usertypeid
}

entity workouttype{
* PK workouttypeid SERIAL
}

entity workout{
* PK workoutid SERIAL
--
* FK workouttypeid
* FK userid
* FK roomid
}

entity pass{
* PK passid SERIAL
--
* FK userid
}

entity reservation{
* PK reservationid SERIAL
--
* FK userid
* FK workoutid
}

entity room{
* PK roomid INT
}

entity roomworkouttype{
* PK roomworkouttypeid SERIAL
--
* FK roomid
* FK workouttypeid
}

gymuser}o==||usertype
workouttype||==o{workout
workout||==o{gymuser
workout||==o{reservation
workout}o==o{room
reservation||==o{gymuser
gymuser}o==||pass

roomworkouttype}|==|{room

workouttype||==|{roomworkouttype







@enduml